# Generated by Django 2.2.6 on 2022-04-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_capacity', models.PositiveIntegerField()),
                ('projector_available', models.BooleanField(default=False)),
            ],
        ),
    ]
